# Generated by Django 4.2.7 on 2025-09-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SportMeet', help_text='Name of the website', max_length=100)),
                ('site_description', models.TextField(blank=True, help_text='Brief description of the website')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for the website', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('currency', models.CharField(default='AUD', help_text='Default currency code', max_length=3)),
                ('timezone', models.CharField(default='Australia/Sydney', help_text='Default timezone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google')], help_text='Social media provider', max_length=20, unique=True)),
                ('client_id', models.CharField(help_text='Client ID or App ID from the social media provider', max_length=500)),
                ('client_secret', models.CharField(help_text='Client Secret or App Secret from the social media provider', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is enabled for login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Media Keys',
                'verbose_name_plural': 'Social Media Keys',
                'ordering': ['provider'],
            },
        ),
    ]
