# Generated by Django 4.2.7 on 2025-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_who_we_are_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cookies',
            field=models.TextField(blank=True, help_text='Markdown/HTML content for Cookies Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faqs',
            field=models.TextField(blank=True, help_text='Markdown/HTML content for FAQs page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy',
            field=models.TextField(blank=True, help_text='Markdown/HTML content for Privacy Policy'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms',
            field=models.TextField(blank=True, help_text='Markdown/HTML content for Terms & Conditions'),
        ),
    ]
