# Generated by Django 4.2.7 on 2025-09-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_cookies_sitesettings_faqs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support',
            field=models.TextField(blank=True, help_text='Markdown/HTML content for Support page'),
        ),
    ]
