# Generated by Django 4.2.7 on 2025-09-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
    ]
