# Generated by Django 4.2.7 on 2025-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_name',
            field=models.CharField(blank=True, help_text='Name of the event host/organizer', max_length=100),
        ),
    ]
