# Generated by Django 4.2.7 on 2025-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
