# Generated by Django 4.2.6 on 2025-09-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventparticipant_payment_intent_id'),
    ]

    operations = [
    ]
