# Generated by Django 4.2.7 on 2025-09-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_venue_event_address_event_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together=set(),
        ),
    ]
