# Generated by Django 4.2.7 on 2025-09-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_add_court_to_availability'),
        ('bookings', '0002_booking_court_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'booking_date', 'start_time', 'court')},
        ),
    ]
