# Generated by Django 4.2.7 on 2025-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
