# Generated by Django 4.2.7 on 2025-09-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_amenity_sport_courttype_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='base_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='base_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.AddField(
            model_name='venue',
            name='booking_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of each court booking in minutes'),
        ),
        migrations.AddField(
            model_name='venue',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Google Maps link to the venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_per_duration',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Price per booking duration', max_digits=10),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_id',
            field=models.CharField(blank=True, help_text='6-digit unique venue identifier', max_length=6, unique=True),
        ),
    ]
