# Generated by Django 4.2.7 on 2025-09-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_court_base_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='booking_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_per_duration',
        ),
        migrations.AddField(
            model_name='court',
            name='booking_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of each court booking in minutes'),
        ),
        migrations.AddField(
            model_name='court',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional court images'),
        ),
        migrations.AddField(
            model_name='court',
            name='price_per_duration',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Price per booking duration', max_digits=10),
        ),
    ]
