# Generated by Django 4.2.7 on 2025-09-23 05:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0006_add_court_to_availability'),
        ('events', '0005_remove_event_venue_event_address_event_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (e.g., WELCOME10)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the discount', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the discount')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage value', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use this discount', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this discount can be used (null = unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('user_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of times a single user can use this discount')),
                ('first_time_only', models.BooleanField(default=False, help_text='Can only be used by first-time users')),
                ('applicable_to_venues', models.BooleanField(default=True)),
                ('applicable_to_events', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
                ('specific_events', models.ManyToManyField(blank=True, help_text='Specific events this discount applies to (empty = all events)', to='events.event')),
                ('specific_venues', models.ManyToManyField(blank=True, help_text='Specific venues this discount applies to (empty = all venues)', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('venue', 'Venue Booking'), ('event', 'Event Booking')], max_length=20)),
                ('booking_id', models.PositiveIntegerField(help_text='ID of the booking/event participation')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='discounts.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Usage',
                'verbose_name_plural': 'Discount Usage Records',
                'db_table': 'discount_usage',
                'ordering': ['-used_at'],
                'unique_together': {('discount', 'user', 'booking_id', 'booking_type')},
            },
        ),
    ]
